baseURL = "https://bu4ak.github.io"
languageCode = "ru"
staticDir = ["assets"]
theme = "anatole"
#title = "title"

[taxonomies]
tag = "tags"

[params]
author = "Igor Buchakov"
customCss = ["css/custom.css"]
description = "Hi there. I am a backend developer."
profilePicture = "images/ava.jpeg"
title = "Igor Buchakov"
# displayMode = "dark"
# disableThemeSwitcher = true
