## Social links
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/igor-buchakov-2a322119a"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/bu4ak"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/bu4akov"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:igorbu4@gmail.com"

[[socialIcons]]
icon = "fab fa-telegram"
title = "telegram"
url = "https://t.me/igorbu4"
